### ISSUE TITLE
Error when running format-sql.el on Emacs-24.5 on Windows 

### ISSUE THREAD

**Issue by sonicpro** [expez/.emacs.d#1]
Python 3.6 installed along with the format-sql package.

When running either M-x format-sql-buffer or M-x format-sql-region the following error occurs:

c:\Users\myname\AppData\Local\Temp\format-sql15512kQb.sql

Traceback (most recent call last):
  File "c:\users\myname\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\myname\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\myname\AppData\Local\Programs\Python\Python36-32\Scripts\format-sql.exe\__main__.py", line 9, in <module>
  File "c:\users\myname\appdata\local\programs\python\python36-32\lib\site-packages\format_sql\main.py", line 83, in main
    _write_back(filename, lines, args.dry_run)
  File "c:\users\myname\appdata\local\programs\python\python36-32\lib\site-packages\format_sql\main.py", line 148, in _write_back
    f.write(lines)
TypeError: write() argument must be str, not None

by the way the file c:\Users\myname\AppData\Local\Temp\format-sql15512kQb.sql is empty, i.e. 0-bytes-sized.

**Comment by expez** [comment]
Hi

I don't use this package so I've no idea why it doesn't work as it should for you.  You'll have to open an issue over at the [format-sql project](https://github.com/emacsmirror/format-sql)
